#!/bin/bash

if [[ $# -ne 1 ]]; then
   echo "Usage: $0 <node>"
   exit 1
fi
ssh $1 "echo 1 > /proc/sys/kernel/sysrq"

# put this in the background to avoid a hang.
ssh $1 "echo b > /proc/sysrq-trigger" &
wait

