#! /usr/bin/bash
##title          : cv_install_controller
##description    : Installs an xCAT controller node. Additionally it also configures
##                 the xCAT web service 
##author         : Hans Then & Abhishek Mukherjee
##email          : hans.then@clustervision
##                 abhishek.mukherjee@clustervision.com

#--------------------------------------------------------------------------------------
# Install Trinity stuff
#--------------------------------------------------------------------------------------

# wait for pacemaker to setup controller's floating ip
while ! ping -c1 controller.cluster &>/dev/null; do 
    echo "waiting for controller.cluster to become available @ $(date)";
    sleep 1;
done
source /etc/profile.d/xcat.sh

#--------------------------------------------------------------------------------------
# copy default database configuration
#--------------------------------------------------------------------------------------
mkdir -p /tmp/xcattables

# FIXME: make these configurable
#read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
ETH1=$(ip route get 8.8.8.8 | grep -oP 'dev \K\S+')
ETH2=$(ip route get 10.141.0.0 | grep -oP 'dev \K\S+')

for table in $(ls /tmp/trinity/controller/xcat/tables); do
    sed -e "s/\<eno1\>/$ETH1/g" -e "s/\<eno2\>/$ETH2/g" \
            /tmp/trinity/controller/xcat/tables/$table > /tmp/xcattables/$table;
done

restorexCATdb -p /tmp/xcattables  
chtab key=timezone site.value=$(timedatectl | grep "Time zone" | grep -oP "Time zone: \K\S+")
mknb x86_64

makedhcp -n
makehosts
makedns -n
makeconservercf

#-------------------------------------------------------------------------------------
# Copy the modules environment
#-------------------------------------------------------------------------------------
echo "Start copy modules environment@ $(date)";
nohup cp -rT /tmp/trinity/clustervision /trinity/clustervision &
cp /tmp/trinity/version /trinity/version
if [[ -f /tmp/trinity/site ]]; then
    cp /tmp/trinity/site /trinity/site
fi

#--------------------------------------------------------------------------------------
# Setup local repository
#--------------------------------------------------------------------------------------
echo "Creating installation tree @ $(date)"
XCAT_VERSION=$(lsxcatd -a | awk -F '[ .]' '/^Version/ {printf "%s.%s", $2, $3}')

nohup bash -c "copycds -n centos7 -o $(ls -cr /tmp/trinity/iso/*.iso | head -1) > /dev/null ;\
    mkdir -p /install/post/otherpkgs/centos7/x86_64 ;\
    echo \"Syncing repositories, this may take some time\" ;\
    reposync -n -r xcat-otherpkgs0 -p /install/post/otherpkgs/centos7/x86_64/ > /dev/null ;\
    createrepo /install/post/otherpkgs/centos7/x86_64/ ;\
    yum -y -q install epel-release ;\
    yum -y -q install http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm ;\
    yum-config-manager --add-repo https://xcat.org/files/xcat/repos/yum/${XCAT_VERSION}/xcat-core/xCAT-core.repo ;\
    yum-config-manager --add-repo https://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64/xCAT-dep.repo ;\
    yum-config-manager --disable base centos-openstack-liberty elrepo epel extras updates xcat-2-core xcat-dep ;\
    sed -i "s/192.168.1.254/controller/" /etc/yum.repos.d/* ;\ 
    echo repo creation finished @ \$(date) >> /var/log/postinstall.log" <&- > /dev/null 2>&1 &


#----------------------------------------------------------------------------------------
# Get the Trinity containers
#----------------------------------------------------------------------------------------
systemctl start docker
systemctl start docker-registry
if [ -z ${SITEMASTER} ]; then
    docker build -t controller:5050/trinity /trinity/container
else
    docker pull ${SITEMASTER}:5050/trinity
    docker tag ${SITEMASTER}:5050/trinity controller:5050/trinity
fi
docker push controller:5050/trinity &

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
