#! /usr/bin/bash
##description    : Setup the first round of High Availability.
##                 It prepares the /drbd filesystem and defines the floating ip address.
##                 Runs only on the active node.
##author         : Hans Then 
##email          : hans.then@clustervision


drbdadm primary --force ha_disk
ssh controller-2 drbdadm connect all
drbdadm connect all

mkfs -t ext4 /dev/drbd1
mount -t ext4 /dev/drbd1 /drbd

rm /etc/httpd/logs ; ln -s /var/log/httpd /etc/httpd/logs
rm /etc/httpd/modules ; ln -s /usr/lib64/httpd/modules /etc/httpd/modules
rm /etc/httpd/run ; ln -s /var/run/httpd /etc/httpd/run

mkdir -p /nfshome
cp /tmp/trinity/controller/rootimg/drbd/xcat.conf /drbd/xcat.conf
drbdlinks -c /drbd/xcat.conf initialize_shared_storage
drbdlinks -c /drbd/xcat.conf start

drbdadm disk-options --resync-rate=110M --c-min-rate=0 ha_disk


#-------------------------------------------------------------------
# Now setup the common resources
#-------------------------------------------------------------------
set -x

dev=$(ip route | grep 10.141.0.0/16 | awk '{print $3}')

# Set basic defaults
pcs cluster cib config
pcs -f config property set no-quorum-policy=ignore
pcs -f config resource op defaults timeout="120s"
pcs -f config resource defaults resource-stickiness=100
pcs -f config property set stonith-enabled=false

pcs -f config resource create ip ocf:heartbeat:IPaddr2 ip="10.141.255.254" \
       iflabel="xCAT" cidr_netmask="16" nic="$dev" op monitor interval="37s"

# Give the first node a slight preference.
pcs -f config constraint location ip prefers controller-1.cluster=50

pcs cluster cib-push config


pcs status

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
