#! /usr/bin/bash
##description    : The third round of High Availability.
##                 This will setup:
##                 1. Pacemaker configuration for the OpenStack Controller services
##                 This needs to be called after cv_install_dockerize.
##                 TODO: add openstack and trinity_api to this setup (contents of cv_install_openstack_on_controller)
##author         : Hans Then
##email          : hans.then@clustervision

#--------------------------------------------------------------------------
# Setup pacemaker
#--------------------------------------------------------------------------
pcs cluster cib config
# Setup high availability for the docker containers
pcs -f config resource create docker systemd:docker op monitor interval="37s"
pcs -f config resource clone docker clone-node-max=1 notify=false

pcs -f config resource create galera systemd:galera op monitor interval="37s"
pcs -f config resource clone galera clone-node-max=1 notify=false

pcs -f config resource create rabbitmq systemd:rabbitmq op monitor interval="37s"
pcs -f config resource create keystone systemd:keystone op monitor interval="37s"
pcs -f config resource create glance systemd:glance op monitor interval="37s"
pcs -f config resource create nova-controller systemd:nova-controller op monitor interval="37s"

pcs -f config resource group add grp_OpenStack rabbitmq keystone glance nova-controller
#pcs -f config resource clone grp_OpenStack clone-node-max=1 notify=false

pcs -f config constraint colocation add grp_OpenStack ip
pcs -f config constraint order start galera-clone then start grp_OpenStack

pcs cluster cib-push config

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
