#!/usr/bin/env bash
##title          : cv_install_containers
##description    : Sets up a dockerized infrastructure.
##                 The following services are dockerized
##                   MariaDB (Database)
##                   RabbitMQ (Message Queue)
##                   Keystone (OpenStack Identity)
##                   Glance (OpenStack Image)
##                   Nova controller (OpenStack Compute: controller part)
##author         : Abhishek Mukherjee, Hans Then
##email          : abhishek.mukherjee@clustervision.com, hans.then@clustervision.com

#------------------------------------------------------------------------------
# Setup the dockerized components
#------------------------------------------------------------------------------
systemctl start docker
REGISTRY="controller:5050"
TOPDIR="/trinity"
profiles=(
  "galera"
  "rabbitmq"
  "keystone"
  "glance"
  "nova_controller"        
)

for profile in "${profiles[@]}"; do
  if ! docker images | grep ${REGISTRY}/${profile}; then
     echo "waiting for docker image ${REGISTRY}/${profile}"
     sleep 1
     continue
  fi
  cp -LrT /tmp/${TOPDIR}/${profile}/host/rootimg /
done

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
